name: Build wheels on multiple OS

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip build --user
    - name: Build wheels
      run: |
        python3 -m build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/biogeme-optimization*.whl

  pypi-publish:
    name: upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist/


      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
